import './vendor';

import './components/header'
import './components/section-services'
import './components/tabs'
import './components/section-slider'
import './components/dropdown'
import './components/section-terminals'
import './components/section-slider-terminal'
import './components/contacts-form'
import './components/section-text'
import './components/show-more'
import './components/free-slider'
import './components/section-description'
import './components/section-about-timeline'
