import './vendor';

import './components/header'
import './components/mobile-nav'
import './components/section-services'
import './components/tabs'
import './components/section-slider'
import './components/dropdown'
import './components/section-terminals'
import './components/section-slider-terminal'
import './components/contacts-form'
import './components/section-contacts-form-white'
import './components/section-text'
import './components/free-slider'
import './components/section-description'
import './components/section-about-timeline'
import './components/section-news'
import './components/scroll-to'
